server:
  port: 9001 # 端口
spring:
  application:
    name: service-gateway #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务地址   向nacos注册网关服务
    gateway:
      discovery:
        locator:
          enabled: true  # 使用服务发现路由
      routes:  #设置路由信息
        - id: service-pms #随意填写，建议与服务名保持一致
          uri: lb://service-pms   #必须是服务名称，对应nacos中的服务名
          predicates:
            - Path=/pms/**  #访问路径相匹配 **代表不限层级不限位数
        - id: service-mes #随意填写，建议与服务名保持一致
          uri: lb://service-mes   #必须是服务名称，对应nacos中的服务名
          predicates:
            - Path=/mes/**  #访问路径相匹配 **代表不限层级不限位数